DROP TABLE IF EXISTS exams;

CREATE TABLE exams (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    description VARCHAR(250) NOT NULL,
    date VARCHAR(250) NOT NULL,
    time VARCHAR(250) NOT NULL,
    location VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS students;

CREATE TABLE students (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    universityId VARCHAR(250) NOT NULL,
);